### ISSUE TITLE
Cannot build gerbil

### ISSUE THREAD

**Issue by trev-dev** [jasonprogrammer/gerbil#7]
Using nim 1.6.10
     
```
     Error: Build failed for package: gerbil
        ... Execution failed with exit code 1
        ... Command: /nix/store/liyh44i3przshljrn7r6jfrhff0v56a9-x86_64-unknown-linux-gnu-nim-wrapper-1.6.10/bin/x86_64-unknown-linux-gnu-nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.1 --path:/home/trev/.nimble/pkgs/argparse-3.0.0 --path:/home/trev/.nimble/pkgs/cligen-1.5.21 --path:'/home/trev/.nimble/pkgs/asynctools-#0e6bdc3ed5bae8c7cc9' --path:/home/trev/.nimble/pkgs/httpbeast-0.4.1 --path:'/home/trev/.nimble/pkgs/asynctools-#pr_fix_compilation' --path:/home/trev/.nimble/pkgs/jester-0.5.0 --path:/home/trev/.nimble/pkgs/markdown-0.8.5 --path:/home/trev/.nimble/pkgs/mustache-0.4.3 --path:/home/trev/.nimble/pkgs/nimcrypto-0.5.4 --path:/home/trev/.nimble/pkgs/unicodedb-0.11.1 --path:/home/trev/.nimble/pkgs/regex-0.19.0 --path:/home/trev/.nimble/pkgs/isaac-0.1.3 --path:/home/trev/.nimble/pkgs/uuids-0.1.11 --hints:off -o:path/to/gerbil/gerbil path/to/gerbil/src/gerbil.nim
        ... Output: path/to/gerbil/src/gerbilpkg/gcontent.nim:28:10 Warning: use fileExists; existsFile is deprecated [Deprecated]
        ... path/to/gerbil/src/gerbilpkg/gcontent.nim:129:10 Warning: use fileExists; existsFile is deprecated [Deprecated]
        ... path/to/gerbil/src/gerbilpkg/gcontent.nim:137:10 Warning: use dirExists; existsDir is deprecated [Deprecated]
        ... path/to/gerbil/src/gerbilpkg/gcontent.nim:147:8 Warning: method has lock level 0, but another method has <unknown> [LockLevel]
        ... path/to/gerbil/src/gerbilpkg/gcontent.nim:163:16 Error: attempting to call undeclared routine: 'since'
```

**Comment by jasonprogrammer** [comment]
@trev-dev Thanks for reporting, I'll take a look!

**Comment by jasonprogrammer** [comment]
@trev-dev It looks like GitHub closed this issue when I merged the PR just now (if it doesn't work for you, please let me know and I can reopen). I upgraded quite a few files just now (I used a lot of old front-end stuff for this project initially. I would make different front-end decisions if I were to refactor/redo it).

**Comment by trev-dev** [comment]
Any sense of what you'd like to do differently?

**Comment by jasonprogrammer** [comment]
I'm not 100% sure, but I like lightweight frameworks, e.g. Preact, SolidJS, Tonic, Vue, and I like being able to support a multi-page (server-rendered pages with sprinkled JS) way of doing things. What kind of preferences do you have for building front-ends?

**Comment by trev-dev** [comment]
Currently built and serving gerbil on port 5000 :)

I also enjoy light frameworks.  My most recent favorite has been Svelte, but that's mostly for embedded features on existing, crowded websites.  In the context of gerbil I am not sure what to recommend.  That largely depends on what the project's goals are.  My bias would be as close to static/minimal in JS as I can get away with if it's not to be generated entirely from JS to begin with.

**Comment by trev-dev** [comment]
I am also curious about JS interop with nim!
